apiVersion: v1
kind: Service
metadata:
  labels:
    app: qip-design-time-catalog
  name: qip-design-time-catalog
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: qip-design-time-catalog