postgres:
  username: postgres
  password: postgres

global:
  postgres:
    database: postgres
  qip:
    ui:
      port: 30080
    deploy:
      classic:
        enabled: true
      micro:
        enabled: true
