apiVersion: v1
data:
  DYNAMIC_ENGINE_CONSUL_STATE_ENABLED: "true"
  KUBE_DEV_MODE: "true"
  POSTGRES_URL: postgres:5432
  RUNTIME_CATALOG_SERVICE_URL: http://qip-runtime-catalog:8080
kind: ConfigMap
metadata:
  labels:
    app: engine-dev-env
  name: engine-dev-env
