camel.k.logging.color = true
camel.k.logging.json = false
camel.k.logging.level = INFO
quarkus.console.color = ${camel.k.logging.color}
quarkus.log.console.json = ${camel.k.logging.json}
quarkus.log.level = ${camel.k.logging.level}
