/**
 * Validates a fixture document against the tracked schema source.
 *
 * One representation, not two. `schemas/assets/` is the dereferenced build output — untracked,
 * regenerated by `npm -w @netcracker/qip-schemas run build`, and therefore whatever the last build
 * produced. Validating elements against it while the chain document comes from
 * `qip-model/chain.schema.yaml` mixes a derived copy with source, and the two drift with nothing
 * to say so. So everything here reads `schemas/src/main/resources/qip-model/`.
 *
 * ajv resolves `$ref` by lookup, not by fetch, and these schemas ref each other by absolute
 * `http://qubership.org/...` URLs. Every schema in the tree is therefore pre-registered by its
 * `$id` before anything is compiled.
 */
import fs from "node:fs";
import path from "node:path";
import { Ajv, type ValidateFunction } from "ajv";
import yaml from "js-yaml";
import { QIP_MODEL_DIR, SCHEMA_BASE_URL } from "../registry/discriminators.js";

/** The exporter writes this; the schema samples carry the schema's own `$id`. Both are the chain. */
export const EXPORTED_CHAIN_SCHEMA = `${SCHEMA_BASE_URL}chain`;

/** `$schema` as a fixture may write it → the `$id` that actually validates it. */
export function canonicalSchemaId(declared: string): string {
  return declared.endsWith(".schema.yaml") ? declared : `${declared}.schema.yaml`;
}

function collectSchemaFiles(dir: string): string[] {
  return fs
    .readdirSync(dir, { withFileTypes: true, recursive: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".schema.yaml"))
    .map((entry) => path.join(entry.parentPath, entry.name))
    .sort();
}

let cached: Ajv | undefined;

/**
 * An ajv instance with every `qip-model` schema registered.
 *
 * `strict: false` because the schemas carry keywords JSON Schema does not define — `metaInfo` on
 * every file, `discriminator` on `element.schema.yaml` — and they are documentation for the UI
 * rather than validation. Strict mode rejects the whole tree over them.
 */
export function schemaValidator(modelDir = QIP_MODEL_DIR): Ajv {
  if (cached && modelDir === QIP_MODEL_DIR) return cached;

  const ajv = new Ajv({
    strict: false,
    allErrors: true,
    validateFormats: false,
  });

  // Two files under one `$id` is not a duplicate to skip past: whichever sorted first would decide
  // what every fixture validates against, and the other would be dead with nothing to say so.
  const byId = new Map<string, string>();
  for (const file of collectSchemaFiles(modelDir)) {
    const schema = yaml.load(fs.readFileSync(file, "utf-8")) as { $id?: string };
    if (typeof schema?.$id !== "string") continue;
    const first = byId.get(schema.$id);
    if (first !== undefined) {
      throw new Error(
        `two schemas declare $id ${schema.$id}: ` +
          `${path.relative(modelDir, first)} and ${path.relative(modelDir, file)}`,
      );
    }
    byId.set(schema.$id, file);
    ajv.addSchema(schema, schema.$id);
  }

  if (modelDir === QIP_MODEL_DIR) cached = ajv;
  return ajv;
}

export interface ValidationFailure {
  /** The document path the failure sits on, in the form ajv reports it — `/content/elements/0`. */
  instancePath: string;
  message: string;
}

/**
 * Validates one parsed document against the schema its `$schema` names.
 *
 * Returns the failures rather than throwing, because the spec that calls this asserts on the field
 * a corrupted fixture names, and an exception carrying a message is a worse thing to assert over
 * than a list.
 */
export function validateDocument(
  document: unknown,
  modelDir = QIP_MODEL_DIR,
): ValidationFailure[] {
  const declared = (document as { $schema?: unknown })?.$schema;
  if (typeof declared !== "string") {
    return [{ instancePath: "", message: "the document declares no $schema" }];
  }

  const ajv = schemaValidator(modelDir);
  const id = canonicalSchemaId(declared);
  const validate = ajv.getSchema(id) as ValidateFunction | undefined;
  if (!validate) {
    return [{ instancePath: "", message: `no schema registered under ${id}` }];
  }

  if (validate(document)) return [];
  return (validate.errors ?? []).map((error) => ({
    instancePath: error.instancePath,
    message: `${error.instancePath || "/"} ${error.message ?? "is invalid"}`,
  }));
}
