apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-runtime-catalog-pod-secrets
  labels:
    app: {{ .Release.Name }}-runtime-catalog
stringData:
  consul_admin_token: {{ .Values.global.consul.adminToken | quote }}
