apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  type: NodePort
  ports:
    - name: "8500"
      port: 8500
      targetPort: 8500
      nodePort: 30500
    - name: "8600"
      port: 8600
      targetPort: 8600
    - name: 8600-udp
      port: 8600
      protocol: UDP
      targetPort: 8600
  selector:
    app: consul