apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: {{ .Release.Name }}-camel-k
spec:
  build:
    registry:
      address: ghcr.io
      organization: qubership
    maven:
      settings:
        configMapKeyRef:
          key: settings.xml
          name: maven-settings
