def message = exchange.getMessage()
message.setBody(message.getBody(String) + '|reuse')
message.setHeader('X-Reuse-Trace', message.getHeader('X-Reuse-Trace', String) + '|reuse')
exchange.setProperty('reuseTrace', exchange.getProperty('reuseTrace', String) + '|reuse')
exchange.setProperty('reuseCount', exchange.getProperty('reuseCount', Integer) + 1)
