scrape_configs:
  - job_name: 'qip-engine'
    static_configs:
      - targets: ['qip-engine:8080']
    metrics_path: /actuator/prometheus
  - job_name: 'qip-engine-quarkus'
    static_configs:
      - targets: ['qip-engine-quarkus:8080']
