---
openapi: 3.1.0
components:
  schemas:
    CheckpointDTO:
      description: Information about checkpoint in session
      type: object
      properties:
        id:
          type: string
          description: Internal id of this record
        checkpointElementId:
          type: string
          description: Element id of passed checkpoint on chain graph
        timestamp:
          type: string
          description: Timestamp when checkpoint were passed
    CheckpointSessionDTO:
      description: Single chain session with available checkpoints list
      type: object
      properties:
        id:
          type: string
          description: Id of the session
        started:
          type: string
          description: Date time of session start
        finished:
          type: string
          description: Date time of session end
        duration:
          type: integer
          format: int64
          description: "Duration of session execution, in ms"
        executionStatus:
          description: "Duration of session execution, in ms"
          type: string
          $ref: "#/components/schemas/ExecutionStatus"
        chainId:
          type: string
          description: Id of the chain it was executed on
        chainName:
          type: string
          description: Name of the chain it was executed on
        engineAddress:
          type: string
          description: engine pod ip address on which chain was executed
        loggingLevel:
          type: string
          description: Value of logging level on a chain at a time chain was executed
        snapshotName:
          type: string
          description: Deployed snapshot name for the chain
        correlationId:
          type: string
          description: Correlation id for that execution (if it was set)
        checkpoints:
          type: array
          items:
            $ref: "#/components/schemas/CheckpointDTO"
          description: List of available checkpoints for that session
    ExecutionStatus:
      description: Status of the element or session
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETED_NORMALLY
      - COMPLETED_WITH_WARNINGS
      - COMPLETED_WITH_ERRORS
      - CANCELLED_OR_UNKNOWN
    LiveExchangeDTO:
      description: Information about Live exchange
      type: object
      properties:
        exchangeId:
          type: string
          description: Exchange id
        deploymentId:
          type: string
          description: Deployment id
        sessionId:
          type: string
          description: Session id
        chainId:
          type: string
          description: Chain id
        duration:
          type: integer
          format: int64
          description: "Duration of current exchange, in ms"
        sessionDuration:
          type: integer
          format: int64
          description: "Duration of the whole session exchange participates in, in\
            \ ms"
        sessionStartTime:
          type: integer
          format: int64
          description: Session start timestamp
        sessionLogLevel:
          description: Current session log level
          type: string
          $ref: "#/components/schemas/SessionsLoggingLevel"
        main:
          type: boolean
          description: Is current exchange main (initial)
    SessionsLoggingLevel:
      type: string
      enum:
      - "OFF"
      - ERROR
      - INFO
      - DEBUG
info:
  description: REST API of QIP Engine Microservice
  x-api-kind: no-bwc
  title: QIP Engine
  version: v1
servers:
- url: /
tags:
- name: checkpoint-session-controller
  description: Checkpoint Session Controller
- name: live-exchanges-controller
  description: Live Exchanges Controller
- name: session-controller
  description: Session Controller
paths:
  /v1/engine/chains/{chainId}/sessions/failed:
    get:
      description: List all failed sessions with available checkpoints for specified
        chain
      x-api-kind: bwc
      tags:
      - checkpoint-session-controller
      parameters:
      - description: Chain id
        name: chainId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CheckpointSessionDTO"
      summary: Get Failed Chain Sessions Info
  /v1/engine/chains/{chainId}/sessions/{sessionId}/checkpoint-elements/{checkpointElementId}/retry:
    post:
      description: Execute chain retry from specified non-failed checkpoint
      x-api-kind: bwc
      tags:
      - checkpoint-session-controller
      parameters:
      - description: Chain id
        name: chainId
        in: path
        required: true
        schema:
          type: string
      - description: Checkpoint element id (could be found on chain graph in checkpoint
          element itself)
        name: checkpointElementId
        in: path
        required: true
        schema:
          type: string
      - description: Session id
        name: sessionId
        in: path
        required: true
        schema:
          type: string
      - description: "Idempotency header, which will be used to identify duplicate\
          \ request"
        name: X-Idempotency-Key
        in: header
        schema:
          type: string
          default: ""
      - description: "Enable TraceMe header, which will force session to be logged"
        name: traceMe
        in: header
        schema:
          type: boolean
          default: false
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "201":
          description: Created
      summary: Retry From Checkpoint
  /v1/engine/chains/{chainId}/sessions/{sessionId}/retry:
    post:
      description: Execute chain retry from saved latest non-failed checkpoint
      x-api-kind: bwc
      tags:
      - checkpoint-session-controller
      parameters:
      - description: Chain id
        name: chainId
        in: path
        required: true
        schema:
          type: string
      - description: Session id
        name: sessionId
        in: path
        required: true
        schema:
          type: string
      - description: "Idempotency header, which will be used to identify duplicate\
          \ request"
        name: X-Idempotency-Key
        in: header
        schema:
          type: string
          default: ""
      - description: "Enable TraceMe header, which will force session to be logged"
        name: traceMe
        in: header
        schema:
          type: boolean
          default: false
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "201":
          description: Created
      summary: Retry From Last Checkpoint
  /v1/engine/live-exchanges:
    get:
      description: Get top N running exchanges ordered by execution time DESC
      tags:
      - live-exchanges-controller
      parameters:
      - schema:
          type: integer
          default: 10
          exclusiveMinimum: 0
        name: limit
        in: query
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LiveExchangeDTO"
      summary: Get Live Exchanges
  /v1/engine/live-exchanges/{deploymentId}/{exchangeId}:
    delete:
      description: Try to kill specified exchange
      tags:
      - live-exchanges-controller
      parameters:
      - description: Deployment ID
        name: deploymentId
        in: path
        required: true
        schema:
          type: string
          pattern: \S
      - description: Exchange ID
        name: exchangeId
        in: path
        required: true
        schema:
          type: string
          pattern: \S
      responses:
        "204":
          description: No Content
      summary: Kill Exchange
  /v1/engine/sessions:
    get:
      description: List all sessions with available checkpoints by their ids
      tags:
      - session-controller
      parameters:
      - description: List of the session ids separated by comma
        name: ids
        in: query
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CheckpointSessionDTO"
      summary: Find Sessions
