apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui-{{ .Values.global.blueGreenVersion }}
  labels:
    app: {{ .Release.Name }}-ui-{{ .Values.global.blueGreenVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui-{{ .Values.global.blueGreenVersion }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui-{{ .Values.global.blueGreenVersion }}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/routes.conf
              subPath: routes.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Release.Name }}-ui-nginx-conf
