package org.qubership.integration.platform.ai.skill.workspace;

/** Typed artifact slots in a per-conversation {@link SkillWorkspace}. */
public enum SkillArtifactType {
  RAW_USER_REQUEST,
  REQUIREMENT_BRIEF,
  DECISION_TRACE,
  SELECTED_PATTERN,
  ELEMENT_SKELETON,
  NAMING_MANIFEST,
  CONFIGURED_TRIGGER_SET,
  CHAIN_STRUCTURE,
  CHAIN_PLAN_GRAPH,
  GRAPH_PATCH,
  GRAPH_PATCH_ARTIFACT,
  GRAPH_ASSEMBLY_RESULT,
  COMPILER_VALIDATION_BUNDLE,
  GENERATOR_PLAN_MANIFEST,
  COMPILER_STATUS,
  PRE_BUILD_VALIDATION,
  PLAN_CAPTURE_OUTCOME,
  IMPLEMENT_PIPELINE_STATE,
  MATERIALIZATION_MAP,
  POST_BUILD_VALIDATION,
  RECONCILE_RESULT,
  CATALOG_CHAIN_SNAPSHOT,
  HITL_CHECKPOINT
}
