import { mkdirSync, rmSync, writeFileSync } from "fs";
import path from "path";
import { SchemaResolver } from "./schemaResolver";
import { generateTypes } from "./generateTypes";

const PROJECT_ROOT = process.cwd();
const ASSETS_DIR = path.join(PROJECT_ROOT, "assets");
const TYPES_DIR = path.join(PROJECT_ROOT, "types");
const DIST_DIR = path.join(PROJECT_ROOT, "dist");

const BANNER = "// AUTO-GENERATED by src/main/scripts/build.ts — do not edit.\n";

function clean(): void {
  rmSync(ASSETS_DIR, { recursive: true, force: true });
  rmSync(TYPES_DIR, { recursive: true, force: true });
  rmSync(DIST_DIR, { recursive: true, force: true });
}

function buildMjs(entries: ReadonlyArray<readonly [string, string]>): string {
  const body = entries
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
  return `${BANNER}export const schemasByType = Object.freeze({\n${body}\n});\n`;
}

function buildDts(entries: ReadonlyArray<readonly [string, string]>): string {
  const union = entries.map(([k]) => `  | ${JSON.stringify(k)}`).join("\n");
  return (
    `${BANNER}` +
    `export * from "../types/index";\n` +
    `export type SchemaType =\n${union};\n` +
    `export declare const schemasByType: Readonly<Record<SchemaType, string>>;\n`
  );
}

function generateRuntimeIndex(resolvedSchemas: Map<string, string>): void {
  const entries = [...resolvedSchemas.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  );

  mkdirSync(DIST_DIR, { recursive: true });
  writeFileSync(path.join(DIST_DIR, "index.mjs"), buildMjs(entries));
  writeFileSync(path.join(DIST_DIR, "index.d.ts"), buildDts(entries));

  console.log(
    `Wrote dist/index.mjs and dist/index.d.ts with ${entries.length} schemas.`,
  );
}

async function build(): Promise<void> {
  clean();
  const resolvedSchemas = await new SchemaResolver().resolveAllSchemas();
  await generateTypes();
  generateRuntimeIndex(resolvedSchemas);
}

async function main(): Promise<void> {
  const command = process.argv[2] ?? "build";
  switch (command) {
    case "build":
      await build();
      return;
    case "clean":
      clean();
      return;
    default:
      console.error(`Unknown command: ${command}. Use 'build' or 'clean'.`);
      process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
