/**
 * The compiled DTO library a specification produces, and the three things that regenerate it.
 *
 * Covers `compiled-library-controller` whole, which is one operation:
 * `GET /v1/models/{modelId}/dto/jar`. There is no upload, no listing and no delete — the jar is
 * generated by codegen from the specification and stored on the `SystemModel`, so the only way to
 * change it is to change the specification or the service it belongs to. That is why a spec about
 * one read endpoint exercises three write paths.
 *
 * **The lever is a specification import, never an upload**: there is no endpoint that accepts a
 * jar. This file covers the catalog side of it — that a library appears, is served, and is rebuilt.
 * The **behavioral** use of a library, a Groovy script resolving the generated class and the
 * engine's compiled-script cache noticing when it moves, is
 * `specs/runtime/script-external-library.spec.ts`.
 *
 * Four shapes measured rather than assumed:
 *
 * - **Only two protocols compile.** `grep -rn "@TargetProtocol"` returns `GraphQLCodeGenerator`
 *   (GRAPHQL) and `GrpcCodeGenerator` (GRPC). For http, soap, amqp and kafka
 *   `SystemModelBaseService.generateJar` finds no generator and returns null, and the endpoint
 *   answers **204**, not 404 and not an empty jar. GraphQL is the fixture protocol here because it
 *   needs no binary toolchain.
 * - **The jar's name and its package both carry the service name**, by two different sanitizers:
 *   `SystemModelBaseService.buildJarFileName` keeps `-` and `.`, while
 *   `PackageNameUtil.buildPackageName` folds every non-word character to `_`. So a rename moves
 *   both, and `jarFileName` and `packagePath` below spell each rule out.
 * - **A service rename recompiles asynchronously.** `SystemService.updateSystemModelCompiledLibraryAsync`
 *   is `@Async`, so the PUT answers 200 with the old jar still stored and the new one lands a
 *   moment later. The case polls; an assertion made straight after the rename is a race that
 *   passes on a slow stack and fails on a fast one.
 * - **A service archive carries the source and not the jar.** So a re-import has to recompile, and
 *   the case proves it the only way that cannot be faked: the service is deleted first, so the
 *   library the jar endpoint serves afterwards was built by the import.
 */
import { test, expect } from "../../support/fixtures.js";
import type { APIResponse } from "@playwright/test";
import type { Catalog } from "../../support/catalog.js";
import { readSpecificationFixture } from "../../fixtures/templating.js";
import { archiveOf, entryNames } from "../../support/zip.js";
import { tokenized } from "../../support/run.js";
import { ABSENT_UUID } from "../../support/absent.js";

/** The version the GraphQL parser's model is given: it declares none, so the catalog counts. */
const VERSION = "1.0.0";

/**
 * `SystemModelBaseService.buildJarFileName`: `{protocol}-{service}-{model}.jar`.
 *
 * The service folds each name through `[^\d\w_\-.]+ -> _` and lower-cases it. Every name this
 * spec mints is `e2e-{run}-{what}` — lowercase letters, digits and hyphens, all of which the class
 * keeps — so the folding is a no-op here and the expected name is the fixture's own, spelled out.
 */
function jarFileName(protocol: string, serviceName: string): string {
  return `${protocol}-${serviceName}-${VERSION}.jar`;
}

/**
 * `PackageNameUtil.buildPackageName`, as a zip entry prefix.
 *
 * Its rule is stricter than the file name's — every non-word character **and** `_` itself collapses
 * to one `_` — so the hyphens the jar name keeps become underscores here. And a segment not
 * starting with a letter takes a prefix, which is what `1.0.0` gets and neither name does.
 */
function packagePath(serviceName: string, groupName: string): string {
  const underscored = (value: string) => value.replace(/-/g, "_");
  return [
    "org/qubership/integration/engine/graphql/generated",
    underscored(serviceName),
    underscored(groupName),
    `model_${VERSION.replace(/\./g, "_")}`,
  ].join("/");
}

interface LibraryFixture {
  systemId: string;
  serviceName: string;
  groupName: string;
  modelId: string;
}

/** A service of this spec's own carrying one GraphQL specification, so it has a compiled library. */
async function graphqlService(catalog: Catalog, run: string, what: string): Promise<LibraryFixture> {
  const serviceName = tokenized(run, `lib-${what}`);
  const groupName = tokenized(run, `libgrp-${what}`);
  const service = await catalog.createSystem(serviceName, "EXTERNAL");
  try {
    const started = await catalog.importSpecificationGroup(
      service.id,
      groupName,
      readSpecificationFixture("widgets.graphql"),
      "graphql",
    );
    await catalog.awaitSpecificationImport(started);
    return {
      systemId: service.id,
      serviceName,
      groupName,
      modelId: `${service.id}-${groupName}-${VERSION}`,
    };
  } catch (cause) {
    await catalog.deleteSystem(service.id).catch(() => {});
    throw cause;
  }
}

/** The `Content-Disposition` filename, which is where the jar's name is the only place it appears. */
function attachmentName(response: APIResponse): string | undefined {
  const disposition = response.headers()["content-disposition"] ?? "";
  return /filename=([^;]+)/.exec(disposition)?.[1];
}

test("a GraphQL import produces a compiled library, and the jar endpoint serves it", { tag: ["@catalog", "@tier1"] }, async ({ catalog, run }) => {
  const fixture = await graphqlService(catalog, run, "jar");
  try {
    const response = await catalog.compiledLibrary(fixture.modelId);
    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toBe("application/octet-stream");
    expect(
      attachmentName(response),
      "the jar is named for its protocol, its service and its specification version",
    ).toBe(jarFileName("graphql", fixture.serviceName));

    // What the generator produced, not merely that something did: the document declares one object
    // type besides Query and Mutation, and the DTO for it is what a script would reach for.
    const entries = await entryNames(await archiveOf(response));
    const prefix = packagePath(fixture.serviceName, fixture.groupName);
    expect(entries).toEqual([
      "META-INF/MANIFEST.MF",
      `${prefix}/Widget$Builder.class`,
      `${prefix}/Widget.class`,
    ]);
  } finally {
    await catalog.deleteSystem(fixture.systemId).catch(() => {});
  }
});

test("a protocol with no code generator compiles nothing, and the endpoint answers 204", { tag: ["@catalog", "@tier1"] }, async ({ catalog, run }) => {
  const serviceName = tokenized(run, "lib-none");
  const groupName = tokenized(run, "libgrp-none");
  const service = await catalog.createSystem(serviceName, "EXTERNAL");
  try {
    const started = await catalog.importSpecificationGroup(
      service.id,
      groupName,
      readSpecificationFixture("widgets.openapi.yaml"),
      "http",
    );
    const imported = await catalog.awaitSpecificationImport(started);
    // The import succeeded — three operations were parsed — so the 204 below is "no generator for
    // http", never "the import produced nothing".
    expect(imported.operations).toHaveLength(3);

    const response = await catalog.compiledLibrary(`${service.id}-${groupName}-${VERSION}`);
    expect(response.status(), "no @TargetProtocol generator carries HTTP").toBe(204);
    expect(await response.text(), "204 is empty, not an empty jar").toBe("");

    // And a specification id nothing answers to is a 404 carrying the catalog's error envelope,
    // which is the shape that tells the two apart.
    const missing = await catalog.compiledLibrary(ABSENT_UUID);
    expect(missing.status()).toBe(404);
    expect(await missing.json()).toMatchObject({
      serviceName: "Catalog",
      errorMessage: `Can't find system model with id: ${ABSENT_UUID}`,
    });
  } finally {
    await catalog.deleteSystem(service.id).catch(() => {});
  }
});

test("renaming the service regenerates the library under the new name", { tag: ["@catalog", "@tier2"] }, async ({ catalog, run }) => {
  const fixture = await graphqlService(catalog, run, "rename");
  try {
    const before = await catalog.compiledLibrary(fixture.modelId);
    expect(attachmentName(before)).toBe(jarFileName("graphql", fixture.serviceName));
    expect(await entryNames(await archiveOf(before))).toContain(
      `${packagePath(fixture.serviceName, fixture.groupName)}/Widget.class`,
    );

    const renamed = tokenized(run, "lib-renamed");
    await catalog.patchSystem(fixture.systemId, { name: renamed });

    // `updateSystemModelCompiledLibraryAsync` is `@Async`: the PATCH answers with the old jar still
    // stored. Poll rather than assert, and poll on the artifact rather than on a sleep.
    await expect
      .poll(
        async () => attachmentName(await catalog.compiledLibrary(fixture.modelId)),
        { message: "the rename recompiles the library on another thread" },
      )
      .toBe(jarFileName("graphql", renamed));

    // The package moved with it, by the other sanitizer: the class a script resolves is at a new
    // fully-qualified name, which is what makes a rename a lever rather than a cosmetic change.
    const after = await catalog.compiledLibrary(fixture.modelId);
    const entries = await entryNames(await archiveOf(after));
    expect(entries).toContain(`${packagePath(renamed, fixture.groupName)}/Widget.class`);
    expect(
      entries.some((entry) => entry.startsWith(packagePath(fixture.serviceName, fixture.groupName))),
      "nothing is left behind under the old package",
    ).toBe(false);
  } finally {
    await catalog.deleteSystem(fixture.systemId).catch(() => {});
  }
});

test("a service archive import recompiles the library from the source it carries", { tag: ["@catalog", "@tier2"] }, async ({ catalog, run }) => {
  const fixture = await graphqlService(catalog, run, "archive");
  const prefix = packagePath(fixture.serviceName, fixture.groupName);
  try {
    expect((await catalog.compiledLibrary(fixture.modelId)).status()).toBe(200);

    const archive = await catalog.exportSystems([fixture.systemId]);
    const entries = await entryNames(archive);
    // The archive is documents plus the specification source. No jar travels in it, so whatever the
    // import produces below was compiled by the import.
    expect(entries.some((entry) => entry.endsWith("/widgets.graphql")), "the source travels").toBe(true);
    expect(entries.some((entry) => entry.endsWith(".jar")), "the jar does not").toBe(false);

    await catalog.deleteSystem(fixture.systemId);
    expect(
      (await catalog.compiledLibrary(fixture.modelId)).status(),
      "the specification is gone with its service",
    ).toBe(404);

    const response = await catalog.importArchive("/v1/import/system", archive, "services.zip");
    expect(response.status()).toBe(200);
    expect(await response.json()).toEqual([
      { id: fixture.systemId, name: fixture.serviceName, status: "CREATED" },
    ]);

    // Synchronous, unlike the rename: `SystemExportImportService.compileSystemModelLibraries` runs
    // inside the import, so the jar is there by the time the import has answered.
    const rebuilt = await catalog.compiledLibrary(fixture.modelId);
    expect(rebuilt.status()).toBe(200);
    expect(attachmentName(rebuilt)).toBe(jarFileName("graphql", fixture.serviceName));
    expect(await entryNames(await archiveOf(rebuilt))).toEqual([
      "META-INF/MANIFEST.MF",
      `${prefix}/Widget$Builder.class`,
      `${prefix}/Widget.class`,
    ]);
  } finally {
    await catalog.deleteSystem(fixture.systemId).catch(() => {});
  }
});
