apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ai-service-env
data:
  QUARKUS_HTTP_PORT: "8080"
  CATALOG_URL: "http://{{ .Release.Name }}-runtime-catalog:8080"
  STORAGE_INIT_BUCKET_ON_STARTUP: "false"
