apiVersion: v1
kind: Service
metadata:
  labels:
    app: qip-variables-management
  name: qip-variables-management
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: qip-variables-management
