spring:
  application:
    deployment_version: ${DEPLOYMENT_VERSION:v1}

app:
  prefix: qip

qip:
  export:
    legacy-format: false
  cr:
    labels:
      domain: ${app.prefix}-domain
      bg-version: bg-version
    naming:
      prefix: ${app.prefix}-engine-
      chains-configuration:
        suffix: -src-cfg
      service-monitor:
        suffix: ""
      service:
        suffix: ""
      chain:
        suffix-length: 7
      http-route:
        public-suffix: -chain-public-routes
        private-suffix: -chain-private-routes
        egress-suffix: -egress-routes
      engine-routes:
        suffix: -routes
