spring:
  application:
    deployment_version: ${DEPLOYMENT_VERSION:v1}

app:
  prefix: qip

qip:
  export:
    legacy-format: false
  cr:
    labels:
      domain: ${app.prefix}-domain
      bg-version: bg-version
    naming:
      prefix: ${app.prefix}-engine-
      chains-configuration:
        suffix: -src-cfg
      service-monitor:
        suffix: ""
      service:
        suffix: ""
      chain:
        suffix-length: 7
      http-route:
        public-suffix: -chain-public-routes
        private-suffix: -chain-private-routes
        egress-suffix: -egress-routes
      engine-routes:
        suffix: -routes
    build:
      replicas: ${MICRO_DOMAIN_REPLICAS:1}
      container:
        image: ${MICRO_DOMAIN_CONTAINER_IMAGE:}
        args: ${MICRO_DOMAIN_CONTAINER_ARGS:}
        request:
          cpu: ${MICRO_DOMAIN_CONTAINER_REQUEST_CPU:}
          memory: ${MICRO_DOMAIN_CONTAINER_REQUEST_MEMORY:}
        limit:
          cpu: ${MICRO_DOMAIN_CONTAINER_LIMIT_CPU:}
          memory: ${MICRO_DOMAIN_CONTAINER_LIMIT_MEMORY:}
        runAsUser: ${MICRO_ENGINE_CONTAINER_RUN_AS_USER:0}
        runAsNonRoot: ${MICRO_ENGINE_CONTAINER_RUN_AS_NON_ROOT:true}
        seccompProfileType: ${MICRO_ENGINE_CONTAINER_SECCOMP_PROFILE_TYPE:RuntimeDefault}
        allowPrivilegeEscalation: ${MICRO_ENGINE_CONTAINER_ALLOW_PRIVILEGE_ESCALATION:false}
        capabilities:
          drop: ${MICRO_ENGINE_CONTAINER_CAPABILITIES_DROP:ALL}
          add: ${MICRO_ENGINE_CONTAINER_CAPABILITIES_ADD:}
      jvm:
        args: ${MICRO_DOMAIN_JVM_ARGS:}
        jar: ${MICRO_DOMAIN_JVM_JAR:}
      mount:
        emptyDirs: ${MICRO_DOMAIN_EMPTY_DIRS:}
        resources: ${MICRO_DOMAIN_RESOURCES:}
      health:
        liveness:
          enabled: ${MICRO_DOMAIN_HEALTH_LIVENESS_ENABLED:false}
          schema: ${MICRO_DOMAIN_HEALTH_LIVENESS_SCHEMA:}
          initialDelay: ${MICRO_DOMAIN_HEALTH_LIVENESS_INITIAL_DELAY:0}
          timeout: ${MICRO_DOMAIN_HEALTH_LIVENESS_TIMEOUT:0}
          period: ${MICRO_DOMAIN_HEALTH_LIVENESS_PERIOD:0}
          successThreshold: ${MICRO_DOMAIN_HEALTH_LIVENESS_SUCCESS_THRESHOLD:0}
          failureThreshold: ${MICRO_DOMAIN_HEALTH_LIVENESS_FAILURE_THRESHOLD:0}
          probe: ${MICRO_DOMAIN_HEALTH_LIVENESS_PROBE:}
          port: ${MICRO_DOMAIN_HEALTH_LIVENESS_PORT:8080}
        readiness:
          enabled: ${MICRO_DOMAIN_HEALTH_READINESS_ENABLED:false}
          schema: ${MICRO_DOMAIN_HEALTH_READINESS_SCHEMA:}
          initialDelay: ${MICRO_DOMAIN_HEALTH_READINESS_INITIAL_DELAY:0}
          timeout: ${MICRO_DOMAIN_HEALTH_READINESS_TIMEOUT:0}
          period: ${MICRO_DOMAIN_HEALTH_READINESS_PERIOD:0}
          successThreshold: ${MICRO_DOMAIN_HEALTH_READINESS_SUCCESS_THRESHOLD:0}
          failureThreshold: ${MICRO_DOMAIN_HEALTH_READINESS_FAILURE_THRESHOLD:0}
          probe: ${MICRO_DOMAIN_HEALTH_READINESS_PROBE:}
          port: ${MICRO_DOMAIN_HEALTH_READINESS_PORT:8080}
        startup:
          enabled: ${MICRO_DOMAIN_HEALTH_SETUP_ENABLED:false}
          schema: ${MICRO_DOMAIN_HEALTH_SETUP_SCHEMA:}
          initialDelay: ${MICRO_DOMAIN_HEALTH_SETUP_INITIAL_DELAY:0}
          timeout: ${MICRO_DOMAIN_HEALTH_SETUP_TIMEOUT:0}
          period: ${MICRO_DOMAIN_HEALTH_SETUP_PERIOD:0}
          successThreshold: ${MICRO_DOMAIN_HEALTH_SETUP_SUCCESS_THRESHOLD:0}
          failureThreshold: ${MICRO_DOMAIN_HEALTH_SETUP_FAILURE_THRESHOLD:0}
          probe: ${MICRO_DOMAIN_HEALTH_SETUP_PROBE:}
          port: ${MICRO_DOMAIN_HEALTH_SETUP_PORT:8080}
      service-account: ${MICRO_DOMAIN_SERVICE_ACCOUNT:default}
      service:
        enabled: ${MICRO_DOMAIN_SERVICE_ENABLED:true}
      monitoring:
        enabled: ${MICRO_DOMAIN_MONITORING_ENABLED:false}
        interval: ${MICRO_DOMAIN_MONITORING_INTERVAL:30s}
      namespace: ${NAMESPACE:default}
      environment: ${MICRO_DOMAIN_ENVIRONMENT:T(java.util.Collections).emptyMap()}
