---
components:
  schemas:
    CheckpointDTO:
      description: "Information about checkpoint in session"
      properties:
        checkpointElementId:
          description: "Element id of passed checkpoint on chain graph"
          type: "string"
        id:
          description: "Internal id of this record"
          type: "string"
        timestamp:
          description: "Timestamp when checkpoint were passed"
          type: "string"
      type: "object"
    CheckpointSessionDTO:
      description: "Single chain session with available checkpoints list"
      properties:
        chainId:
          description: "Id of the chain it was executed on"
          type: "string"
        chainName:
          description: "Name of the chain it was executed on"
          type: "string"
        checkpoints:
          description: "List of available checkpoints for that session"
          items:
            $ref: "#/components/schemas/CheckpointDTO"
          type: "array"
        correlationId:
          description: "Correlation id for that execution (if it was set)"
          type: "string"
        duration:
          description: "Duration of session execution, in ms"
          format: "int64"
          type: "integer"
        engineAddress:
          description: "engine pod ip address on which chain was executed"
          type: "string"
        executionStatus:
          description: "Duration of session execution, in ms"
          enum:
          - "IN_PROGRESS"
          - "COMPLETED_NORMALLY"
          - "COMPLETED_WITH_WARNINGS"
          - "COMPLETED_WITH_ERRORS"
          - "CANCELLED_OR_UNKNOWN"
          type: "string"
        finished:
          description: "Date time of session end"
          type: "string"
        id:
          description: "Id of the session"
          type: "string"
        loggingLevel:
          description: "Value of logging level on a chain at a time chain was executed"
          type: "string"
        snapshotName:
          description: "Deployed snapshot name for the chain"
          type: "string"
        started:
          description: "Date time of session start"
          type: "string"
      type: "object"
    LiveExchangeDTO:
      description: "Information about Live exchange"
      properties:
        chainId:
          description: "Chain id"
          type: "string"
        deploymentId:
          description: "Deployment id"
          type: "string"
        duration:
          description: "Duration of current exchange, in ms"
          format: "int64"
          type: "integer"
        exchangeId:
          description: "Exchange id"
          type: "string"
        main:
          description: "Is current exchange main (initial)"
          type: "boolean"
        sessionDuration:
          description: "Duration of the whole session exchange participates in, in\
            \ ms"
          format: "int64"
          type: "integer"
        sessionId:
          description: "Session id"
          type: "string"
        sessionLogLevel:
          description: "Current session log level"
          enum:
          - "OFF"
          - "ERROR"
          - "INFO"
          - "DEBUG"
          type: "string"
        sessionStartTime:
          description: "Session start timestamp"
          format: "int64"
          type: "integer"
      type: "object"
info:
  description: "REST API of Qubership Integration Platform Engine Microservice"
  title: "Qubership Integration Platform Engine"
  version: "v1"
  x-api-kind: "no-bwc"
openapi: "3.1.0"
paths:
  /v1/engine/chains/{chainId}/sessions/failed:
    get:
      description: "List all failed sessions with available checkpoints for specified\
        \ chain"
      operationId: "getFailedChainSessionsInfo"
      parameters:
      - description: "Chain id"
        in: "path"
        name: "chainId"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/CheckpointSessionDTO"
                type: "array"
          description: "OK"
      tags:
      - "checkpoint-session-controller"
      x-api-kind: "bwc"
  /v1/engine/chains/{chainId}/sessions/{sessionId}/checkpoint-elements/{checkpointElementId}/retry:
    post:
      description: "Execute chain retry from specified non-failed checkpoint"
      operationId: "retryFromCheckpoint"
      parameters:
      - description: "Chain id"
        in: "path"
        name: "chainId"
        required: true
        schema:
          type: "string"
      - description: "Session id"
        in: "path"
        name: "sessionId"
        required: true
        schema:
          type: "string"
      - description: "Checkpoint element id (could be found on chain graph in checkpoint\
          \ element itself)"
        in: "path"
        name: "checkpointElementId"
        required: true
        schema:
          type: "string"
      - description: "If passed, Authorization header will be replaced with this value"
        in: "header"
        name: "authorization"
        required: false
        schema:
          default: ""
          type: "string"
      - description: "Enable TraceMe header, which will force session to be logged"
        in: "header"
        name: "traceMe"
        required: false
        schema:
          default: false
          type: "boolean"
      - description: "Idempotency header, which will be used to identify duplicate\
          \ request"
        in: "header"
        name: "X-Idempotency-Key"
        required: false
        schema:
          default: ""
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              description: "If passed, request body will be replaced with this value"
              type: "string"
      responses:
        "200":
          description: "OK"
      tags:
      - "checkpoint-session-controller"
      x-api-kind: "bwc"
  /v1/engine/chains/{chainId}/sessions/{sessionId}/retry:
    post:
      description: "Execute chain retry from saved latest non-failed checkpoint"
      operationId: "retryFromLastCheckpoint"
      parameters:
      - description: "Chain id"
        in: "path"
        name: "chainId"
        required: true
        schema:
          type: "string"
      - description: "Session id"
        in: "path"
        name: "sessionId"
        required: true
        schema:
          type: "string"
      - description: "If passed, Authorization header will be replaced with this value"
        in: "header"
        name: "authorization"
        required: false
        schema:
          default: ""
          type: "string"
      - description: "Enable TraceMe header, which will force session to be logged"
        in: "header"
        name: "traceMe"
        required: false
        schema:
          default: false
          type: "boolean"
      - description: "Idempotency header, which will be used to identify duplicate\
          \ request"
        in: "header"
        name: "X-Idempotency-Key"
        required: false
        schema:
          default: ""
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              description: "If passed, request body will be replaced with this value"
              type: "string"
      responses:
        "200":
          description: "OK"
      tags:
      - "checkpoint-session-controller"
      x-api-kind: "bwc"
  /v1/engine/live-exchanges:
    get:
      description: "Get top N running exchanges ordered by execution time DESC"
      operationId: "getLiveExchanges"
      parameters:
      - description: "Amount of exchanges to view"
        in: "query"
        name: "limit"
        required: false
        schema:
          default: 10
          exclusiveMinimum: 0
          format: "int32"
          type: "integer"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/LiveExchangeDTO"
                type: "array"
          description: "OK"
      tags:
      - "live-exchanges-controller"
  /v1/engine/live-exchanges/{deploymentId}/{exchangeId}:
    delete:
      description: "Try to kill specified exchange"
      operationId: "killExchange"
      parameters:
      - description: "Deployment ID"
        in: "path"
        name: "deploymentId"
        required: true
        schema:
          type: "string"
      - description: "Exchange ID"
        in: "path"
        name: "exchangeId"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
      tags:
      - "live-exchanges-controller"
  /v1/engine/sessions:
    get:
      description: "List all sessions with available checkpoints by their ids"
      operationId: "findSessions"
      parameters:
      - description: "List of the session ids separated by comma"
        in: "query"
        name: "ids"
        required: false
        schema:
          items:
            type: "string"
          type: "array"
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/CheckpointSessionDTO"
                type: "array"
          description: "OK"
      tags:
      - "session-controller"
servers:
- url: "/"
tags:
- description: "Session Controller"
  name: "session-controller"
- description: "Checkpoint Session Controller"
  name: "checkpoint-session-controller"
- description: "Live Exchanges Controller"
  name: "live-exchanges-controller"
