name: Checkstyle Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'checkstyle/**'
      - 'pom.xml'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_maven-module-build.yaml
    with:
      module: checkstyle
    secrets: inherit
