name: Engine Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'engine/**'
      - 'parent/**'
      - 'pom.xml'

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/_maven-module-build.yaml
    with:
      module: engine
      sonar-project-key: ${{ vars.SONAR_ENGINE_PROJECT_KEY }}
    secrets: inherit
