name: Runtime Catalog Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'runtime-catalog/**'
      - 'parent/**'
      - 'pom.xml'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_maven-module-build.yaml
    with:
      module: runtime-catalog
      sonar-project-key: ${{ vars.SONAR_RUNTIME_CATALOG_PROJECT_KEY }}
    secrets: inherit
