name: Schemas Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'schemas/**'

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/_maven-module-build.yaml
    with:
      module: schemas
    secrets: inherit
