name: Sessions Management Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'sessions-management/**'
      - 'parent/**'
      - 'pom.xml'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_maven-module-build.yaml
    with:
      module: sessions-management
      sonar-project-key: ${{ vars.SONAR_SESSIONS_MANAGEMENT_PROJECT_KEY }}
    secrets: inherit
